# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RAPHHH
url: "https://raphhh21.github.io"
email: raphael.t.dev@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Raph's Website
og_image: "https://avatars.githubusercontent.com/u/32976542"
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ""
github_username: raphhh21
minimal_mistakes_skin: dark
search: true

author:
  name: "Raphael"
  avatar: "https://avatars.githubusercontent.com/u/32976542"
  bio: "Aspiring Software Developer"
  links:
    - label: "raphhh21"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raphhh21"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# outputting
permalink: /:categories/:title/
paginate: 12 # number of pages to show
paginate_path: /page:num

repository: "raphhh21/raphhh21.github.io"

plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

category_archive:
  type: liquid
  path: /blog/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # for posts
  - scope:
      path: ""
      type: posts
    values:
        layout: single
        read_time: true
        show_date: true
        author_profile: true
        share: false
        comments: false
        related: true
  # for pages
  - scope:
      path: "_pages"
      type: home
    values:
      layout: single
      author_profile: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
